language: c

compiler: gcc

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -qq update ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libcunit1-dev ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install readline; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install cunit; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export LDFLAGS="-L/usr/local/opt/readline/lib"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CPPFLAGS="-I/usr/local/opt/readline/include"; fi

script:
  - "./bootstrap.sh"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./configure --enable-gcov; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make check; fi

  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./configure; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make check; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - if [ -f ./test-suite.log ]; then cat ./test-suite.log; fi

